# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Gripper controller
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robotiq_85_left_knuckle_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
        robotiq_85_left_knuckle_joint: {p: 100.0, i: 1.0, d: 0.5, i_clamp: 10}
        # robotiq_85_right_knuckle_joint: {p: 1.0, i: 0.0, d: 0.0}
        # robotiq_85_right_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0}
        # robotiq_85_left_inner_knuckle_joint: {p: 1.0, i: 0.0, d: 0.0}
        # robotiq_85_left_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0}
        # robotiq_85_right_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0}

# Trajectory controller
trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    elbow_joint: {trajectory: 0.1, goal: 0.1}
    wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10


controller_list:
  - name: "trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: "gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - robotiq_85_left_knuckle_joint

# gazebo_ros_control:
#   pid_gains:
#         robotiq_85_left_knuckle_joint: {p: 20.0, i: 0.1, d: 0.0}
#         robotiq_85_right_knuckle_joint: {p: 20.0, i: 0.1, d: 0.00}
#         robotiq_85_right_finger_tip_joint: {p: 20.0, i: 0.1, d: 0.00}
#         robotiq_85_left_inner_knuckle_joint: {p: 20.0, i: 0.1, d: 0.00}
#         robotiq_85_left_finger_tip_joint: {p: 20.0, i: 0.1, d: 0.0}
#         robotiq_85_right_finger_tip_joint: {p: 20.0, i: 0.1, d: 0.0}
